[build]
  publish = "dist/"
  command = "npm run build"


[[headers]]
    for = "/img/*"
    [headers.values]
        Cache-Control = "public, max-age=360000"


[[headers]]
    for = "*.ico"
    [headers.values]
        Cache-Control = "public, max-age=360000"


[[headers]]
    for = "*.js"
    [headers.values]
        Cache-Control = "public, max-age=360000"

[[headers]]
    for = "*.css"
    [headers.values]
        Cache-Control = "public, max-age=360000"

