[build]
  publish = "dist/"
  command = "npm run build"


[[headers]]
    for = "*.webp"
    [headers.values]
        Cache-Control = "public, max-age=999999"


[[headers]]
    for = "*.ico"
    [headers.values]
        Cache-Control = "public, max-age=31536000"


[[headers]]
    for = "*.js"
    [headers.values]
        Cache-Control = "public, max-age=31536000"

[[headers]]
    for = "*.css"
    [headers.values]
        Cache-Control = "public, max-age=31536000"

