[build]
  publish = "dist/"
  command = "npm run build && npx inline-assets dist/index.html dist/index.html --htmlmin --cssmin --jsmin && npx inline-assets dist/watch.html dist/watch.html --htmlmin --cssmin --jsmin && npx inline-assets dist/ads.html dist/ads.html --htmlmin --cssmin --jsmin"


[[headers]]
    for = "/img/*"
    [headers.values]
        Cache-Control = "public, max-age=999999"


[[headers]]
    for = "*.ico"
    [headers.values]
        Cache-Control = "public, max-age=31536000"


[[headers]]
    for = "*.js"
    [headers.values]
        Cache-Control = "public, max-age=31536000"

[[headers]]
    for = "*.css"
    [headers.values]
        Cache-Control = "public, max-age=31536000"

