
all:
	cwebp -q 80 alfred.png -o alfred.webp
	cwebp -q 80 bbq.png -o bbq.webp
	cwebp -q 80 calimero.png -o calimero.webp
	cwebp -q 80 chili.png -o chili.webp
	cwebp -q 80 cock.png -o cock.webp
	cwebp -q 80 dildo.png -o dildo.webp
	cwebp -q 80 kud.png -o kud.webp
	cwebp -q 80 mankini.png -o mankini.webp
	cwebp -q 80 milf.png -o milf.webp
	cwebp -q 80 pole.png -o pole.webp
	cwebp -q 80 redis.png -o redis.webp
	cwebp -q 80 sax.png -o sax.webp
	cwebp -q 80 star.png -o star.webp
	cwebp -q 80 store.png -o store.webp
	cwebp -q 80 strip.png -o strip.webp
	cwebp -q 80 uncle.png -o uncle.webp
